import turtle
'''
turtle.speed(0)
for f in range(1,50):
    turtle.forward(f)
    turtle.right(90)

turtle.forward(25)
turtle.circle(-25)
for f in range (35, 100, 10):
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.circle(-f)
turtle.done()
'''
turtle.circle(30)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.left(60)
turtle.circle(30)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.left(60)
turtle.circle(30)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.left(60)
turtle.circle(30)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.left(60)
turtle.circle(30)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.left(60)
turtle.circle(30)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.left(60)
turtle.circle(30)
